- app/controllers/application_controller.rb
- app/lib/gateway/authentication.rb
- app/lib/usecase/jwt_authentication.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- spec/controller/application_controller_spec.rb
- spec/controllers/health_controller_spec.rb
- spec/lib/gateway/authentication_spec.rb
- spec/lib/usecase/jwt_authentication_spec.rb
- spec/rails_helper.rb
- spec/request/health_controller_spec.rb
- spec/request/pdf_generator_controller_spec.rb
This checks for authorisation of the given request
In other apps information on who was the sender was taken from part of the URL
This implementation better follows the J.W.T. spec while making the URLs more flexible/restful
> Authorise requests

- .circleci/config.yml
- .gitignore
- .local/share/pry/pry_history
- .rubocop.yml
- Dockerfile
- app/controllers/pdfs_controller.rb
- app/views/pdfs/_footer.html.erb
- app/views/pdfs/show.html
- app/views/pdfs/show.html.erb
- config/initializers/pdfkit.rb
- spec/request/pdfs_controller_spec.rb
Given the correct payload, a PDF containing all the correct data is generated.
To Do:
Needs to match previous PDFs:
Without summary heading:
[without-summary-haeding.pdf](https://github.com/ministryofjustice/fb-pdf-generator/files/3712060/without-summary-haeding.pdf)
With summary heading:
[with-summary-heading.pdf](https://github.com/ministryofjustice/fb-pdf-generator/files/3712057/with-summary-heading.pdf)
next pr todos:
> [WIP] Generate PDF with data

- config/environments/development.rb
Rails 6 has a whitelist security feature for allowed hosts.
This is unneeded in the development environment, and is blocking local stack testing.
> Allow any host to contact this API in development

- app/controllers/pdfs_controller.rb
- spec/request/pdfs_controller_spec.rb
When the `pdf_heading:` key was missing from the payload, the application blew up.
With this change, if the key is missing it will simply not be displayed. This functionality already existed for the `pdf_subheading:`.
> Allow PDF Heading to be optional

- Gemfile.lock
- app/controllers/concerns/jwt_authentication.rb
- app/lib/gateway/authentication.rb
- app/lib/gateway/public_key.rb
- app/lib/usecase/jwt_authentication.rb
- spec/controller/application_controller_spec.rb
- spec/lib/gateway/public_key_spec.rb
- spec/lib/usecase/jwt_authentication_spec.rb
- spec/spec_helper.rb
- if `access -token-v2` is provided it uses public key mechanism instead to verify jwt token
> compatible with v2 access token

- Makefile
- app/lib/gateway/public_key.rb
- app/lib/usecase/jwt_authentication.rb
- spec/controller/application_controller_spec.rb
- spec/lib/gateway/public_key_spec.rb
- spec/lib/usecase/jwt_authentication_spec.rb
- spec/shared_context/auth_tests.rb
- public key is parsed from json response
- jwt from submitter now sends `iss` as part of payload not headers as described in JWT specification
- this change is backwards compatible with old auth mechanism
> fix public key verification

- Makefile
as this causes issues when calling `make spec`
> remove docker compose volume mount

- .circleci/config.yml
[Trello](https://trello.com/c/OP1n7Bve/181-formalise-docker-build-image-for-circleci)
Replace image from docker hub with aws ecr
> Replace image from docker hub with aws ecr (in test)

- Gemfile
- Gemfile.lock
- config/initializers/metrics_adapter.rb
- deploy/templates/deployment.yaml
- deploy/templates/secrets.yaml
[Trello Card](https://trello.com/c/5cXWL11V/342-request-delay-between-pages)
This PR adds the [metrics adapter gem](https://github.com/ministryofjustice/metrics-adapter) - the [first version](https://github.com/ministryofjustice/metrics-adapter/pull/1).
I am considering 1 second as a slow request and I added via config of the gem.
> Add metrics adapter to the app

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- deploy/templates/secrets.yaml
Two minor improvements for the request delay metrics work.
1. Add the values into the right secrets and make the shared secrets available in helm. PDF generator doesn't use our deploy scripts and inject the helm on the Circleci config.
2. Bum the metrics adapter version to accommodate improvements
> Request between pages improvements

- .circleci/config.yml
We do not want to trigger acceptance tests until after the spec tests have passed.
> Trigger acceptance tests if specs pass

- deploy/templates/deployment.yaml
Kubernetes has been upgraded to 1.16. These changes are required for the resources to continue working.
Followed the guide here:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/apiversion-changes-k8s-1-16.html#resources-deployed-using-helm-charts
https://trello.com/c/w8d8G6RM/696-cloud-platform-kubernetes-update
> Update kubernetes resources

- app/controllers/pdfs_controller.rb
- config/routes.rb
- spec/request/pdfs_controller_spec.rb
Previously the controller was using www-form-urlencoded and Rails was unable to parse the params correctly. This was failing specifically when users entered a "%" character into their submissions.
Swap to use the params itself and symbolize all the param keys.
Co-authored-by: Tomas Destefi <tomas.destefi@digital.justice.gov.uk>
> Change controller to read JSON requests

- app/views/pdfs/show.html.erb
We need to allow for HTML tags to be correctly parsed in the generated PDF. Previously it was printing the `<strong>` tags.
Co-authored-by: Tomas Destefi <tomas.destefi@digital.justice.gov.uk>
Co-authored-by: Natalie Seeto <natalie.seeto@digital.justice.gov.uk>
> Allow HTML tags in PDF sub headings

- app/views/pdfs/show.html.erb
Reverts ministryofjustice/fb-pdf-generator#182
We have decided not to do this for now.
> Revert "Allow HTML tags in PDF sub headings"

- spec/request/pdfs_controller_spec.rb
Trello: https://trello.com/c/ARVs1ROm/1128-add-acceptance-test-testing-special-characters
This PR adds a test to ensure special characters are accepted in submissions.
> Test special characters

- deploy/fb-pdf-generator-chart/templates/deployment.yaml
We are continuing to investigate networking issues across our apps
inside the Cloud Platform infrastructure. One suggestion is to increase
the initialDelaySeconds to 15 seconds which we have previously done on
the datastore app.
> Increase initialDelaySeconds

- Dockerfile
The deployment was failing because the pipeline would attempt to use the latest version of bundler. Lock the bundler version to 2.1.4 to prevent this failure from occuring.
The bundler lock version step is also done in the fb-publisher Dockerfile.
Co-authored-by: Steven Leighton <steven.leighton@digital.justice.gov.uk>
> Lock bundler version in the Dockerfile

- .circleci/config.yml
Github have recently rotated their RSA SSH host key: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/
As a result, the public key is no longer up to date in the `known_host` file.
The 'checkout' step automatically adds the required authenticity keys for interacting with Github. Adding this job allows the acceptance test and smoke tests steps to interact with Github.
CircleCI run:
https://app.circleci.com/pipelines/github/ministryofjustice/fb-pdf-generator/1277/workflows/177e3cb2-2833-45e1-9c5f-b82e0dde7213
> GitHub key

- .circleci/config.yml
`Job was rejected because this version of Docker is not supported on this resource class. Try removing the version of Docker in your .circleci/config.yml and re-running`
> CDPT-3035: Remove docker version
