Gemfile, Gemfile.lock, app/controllers/pdfs_controller.rb, app/views/pdfs/_footer.html.erb, app/views/pdfs/show.html.erb, config/initializers/pdfkit.rb, spec/request/pdfs_controller_spec.rb
=> Add Footer to PDF's

app/views/pdfs/_pdf_style.css.erb, app/views/pdfs/show.html.erb, spec/request/pdfs_controller_spec.rb
=> Render questions to table and style

app/views/pdfs/show.html.erb, spec/request/pdfs_controller_spec.rb
Reverts ministryofjustice/fb-pdf-generator#31
=> Revert "use human_value from payload for pdf"

app/views/pdfs/show.html.erb, spec/request/pdfs_controller_spec.rb
Originally wanted to do this in the submitter. 
But after some trying this is much much simpler. 
This PR should fix file upload names as well as capitalising boolen Yes/No
=> prefer human_value over machine value

README.markdown
Add a Readme with basic setup.
=> Add simple readme explaining how to run the server

app/controllers/concerns/jwt_authentication.rb, spec/controller/application_controller_spec.rb
[Trello](https://trello.com/c/DaEXYM24/109-switch-to-new-auth-method-deprecate-old-auth-method-4-4)
V2 is now in use so we no longer need any related v1 authentication
code.
Co-authored-by: Brendan Butler <brendan.butler@digital.justice.gov.uk>
=> Remove v1 authentication code

Gemfile.lock
Reverts ministryofjustice/fb-pdf-generator#90
=> Revert "Bump pdfkit from 0.8.4.1 to 0.8.4.2"

Dockerfile
This can give a boost to our bundle install (I see at you Nokogiri!).
"Some believe it is only great power that can hold evil in check, but that is not what I have found. It is the small everyday deeds of ordinary folk that keep the darkness at bay. " Ok, I felt mention LOTR for this PR. 🙈
=> Add 4 workers to bundle install to improve performance

.circleci/config.yml
Necessary for the upcoming pentest work
https://trello.com/c/Uc99fjuD/700-deploy-platform-in-pentest-environment
=> Add deploy to pentest environment step

.circleci/config.yml
We only want to push an image if the tests have passed.
Also trigger acceptance tests once the image has been pushed.
=> Push image only if tests pass

.circleci/config.yml
Pentesting is complete so these can be removed
=> Remove pentest deployment

.circleci/config.yml
We now want to trigger the acceptance tests only after a successful build and deploy.
=> Trigger acceptance tests after build and deploy step

.circleci/config.yml
Add smoke tests to the app. Work done in ministryofjustice/fb-deploy#21
=> Add smoke test after deployment to live

config/initializers/filter_parameter_logging.rb
The sections contains user answers and even if the pdf parameter
is not being used the legacy runner sends it pdf
=> Do not log the sections neither pdf params

Gemfile, Gemfile.lock, config/initializers/sentry.rb
Also add http_logger as well as turning on performance metrics
=> Migrate to new Sentry gem

.circleci/config.yml, deploy-eks/fb-pdf-generator-chart/Chart.yaml, deploy-eks/fb-pdf-generator-chart/templates/config_map.yaml, deploy-eks/fb-pdf-generator-chart/templates/deployment.yaml, deploy-eks/fb-pdf-generator-chart/templates/network_policy.yaml, deploy-eks/fb-pdf-generator-chart/templates/secrets.yaml, deploy-eks/fb-pdf-generator-chart/templates/service.yaml
Deploying to old and new clusters at the same deployment (while we are migrating).
=> Add templates for the new cluster

Gemfile.lock
Reverts ministryofjustice/fb-pdf-generator#342
=> Revert "Bump pdf-reader from 2.5.0 to 2.8.0"

.circleci/config.yml
App will deploy to both clusters.
=> Added config to deploy to live-dev and live-production in EKS

Gemfile.lock
=> Update Rack to 2.2.3.1

.circleci/config.yml
- Rotate the fingerprint for cloning secrets
- Use deployment configuration and platform contexts
=> Update circleci deployment config

Gemfile, Gemfile.lock, spec/rails_helper.rb, spec/request/pdfs_controller_spec.rb
[Trello](https://trello.com/c/Wn6aaSOU/3788-dependabot-cleanup)
Remove patch dependencies
Update dependencies
Replace Timecop by TimeHelpers
=> Remove patch dependencies

Dockerfile
=> CDPT-3035: Update ruby image
